package entities;
// Generated 21/08/2016 12:05:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Academia generated by hbm2java
 */
public class Academia  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String senha;
     private String telefone;
     private int cnpj;
     private String estado;
     private String cidade;
     private String endereco;
     private Set servicos = new HashSet(0);

    public Academia() {
    }

	
    public Academia(String email, String senha, String telefone, int cnpj, String estado, String cidade, String endereco) {
        this.email = email;
        this.senha = senha;
        this.telefone = telefone;
        this.cnpj = cnpj;
        this.estado = estado;
        this.cidade = cidade;
        this.endereco = endereco;
    }
    public Academia(String email, String senha, String telefone, int cnpj, String estado, String cidade, String endereco, Set servicos) {
       this.email = email;
       this.senha = senha;
       this.telefone = telefone;
       this.cnpj = cnpj;
       this.estado = estado;
       this.cidade = cidade;
       this.endereco = endereco;
       this.servicos = servicos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public int getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(int cnpj) {
        this.cnpj = cnpj;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public Set getServicos() {
        return this.servicos;
    }
    
    public void setServicos(Set servicos) {
        this.servicos = servicos;
    }




}


