package entities;
// Generated 21/08/2016 12:05:28 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String email;
     private String telefone;
     private String apelido;
     private String senha;
     private Integer cpf;
     private String exameMedico;
     private String estado;
     private String cidade;
     private String endereco;
     private Date validadeSaldo;
     private BigDecimal saldo;
     private Date ultimaRecarga;
     private Set historicoTransacaos = new HashSet(0);
     private Set historicoCreditos = new HashSet(0);

    public Cliente() {
    }

    public Cliente(String nome, String email, String telefone, String apelido, String senha, Integer cpf, String exameMedico, String estado, String cidade, String endereco, Date validadeSaldo, BigDecimal saldo, Date ultimaRecarga, Set historicoTransacaos, Set historicoCreditos) {
       this.nome = nome;
       this.email = email;
       this.telefone = telefone;
       this.apelido = apelido;
       this.senha = senha;
       this.cpf = cpf;
       this.exameMedico = exameMedico;
       this.estado = estado;
       this.cidade = cidade;
       this.endereco = endereco;
       this.validadeSaldo = validadeSaldo;
       this.saldo = saldo;
       this.ultimaRecarga = ultimaRecarga;
       this.historicoTransacaos = historicoTransacaos;
       this.historicoCreditos = historicoCreditos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getApelido() {
        return this.apelido;
    }
    
    public void setApelido(String apelido) {
        this.apelido = apelido;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Integer getCpf() {
        return this.cpf;
    }
    
    public void setCpf(Integer cpf) {
        this.cpf = cpf;
    }
    public String getExameMedico() {
        return this.exameMedico;
    }
    
    public void setExameMedico(String exameMedico) {
        this.exameMedico = exameMedico;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public Date getValidadeSaldo() {
        return this.validadeSaldo;
    }
    
    public void setValidadeSaldo(Date validadeSaldo) {
        this.validadeSaldo = validadeSaldo;
    }
    public BigDecimal getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }
    public Date getUltimaRecarga() {
        return this.ultimaRecarga;
    }
    
    public void setUltimaRecarga(Date ultimaRecarga) {
        this.ultimaRecarga = ultimaRecarga;
    }
    public Set getHistoricoTransacaos() {
        return this.historicoTransacaos;
    }
    
    public void setHistoricoTransacaos(Set historicoTransacaos) {
        this.historicoTransacaos = historicoTransacaos;
    }
    public Set getHistoricoCreditos() {
        return this.historicoCreditos;
    }
    
    public void setHistoricoCreditos(Set historicoCreditos) {
        this.historicoCreditos = historicoCreditos;
    }




}


