package entities;
// Generated 21/08/2016 12:05:28 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * HistoricoTransacao generated by hbm2java
 */
public class HistoricoTransacao  implements java.io.Serializable {


     private Integer id;
     private Cliente cliente;
     private Date dataTransacao;
     private BigDecimal valor;

    public HistoricoTransacao() {
    }

	
    public HistoricoTransacao(Cliente cliente) {
        this.cliente = cliente;
    }
    public HistoricoTransacao(Cliente cliente, Date dataTransacao, BigDecimal valor) {
       this.cliente = cliente;
       this.dataTransacao = dataTransacao;
       this.valor = valor;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getDataTransacao() {
        return this.dataTransacao;
    }
    
    public void setDataTransacao(Date dataTransacao) {
        this.dataTransacao = dataTransacao;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }




}


