package entities;
// Generated 21/08/2016 12:05:28 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Servico generated by hbm2java
 */
public class Servico  implements java.io.Serializable {


     private Integer id;
     private Academia academia;
     private String nome;
     private BigDecimal preco;
     private String tipo;

    public Servico() {
    }

	
    public Servico(Academia academia, String nome, String tipo) {
        this.academia = academia;
        this.nome = nome;
        this.tipo = tipo;
    }
    public Servico(Academia academia, String nome, BigDecimal preco, String tipo) {
       this.academia = academia;
       this.nome = nome;
       this.preco = preco;
       this.tipo = tipo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Academia getAcademia() {
        return this.academia;
    }
    
    public void setAcademia(Academia academia) {
        this.academia = academia;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public BigDecimal getPreco() {
        return this.preco;
    }
    
    public void setPreco(BigDecimal preco) {
        this.preco = preco;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


